version: "3.4"

# volumes:
#   mongo_data:
#     name: appy_mongo_data

# networks:
#   backend:
#   frontend:

services:

  # Monitoring and tracing the different services
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
  
  # Kraken API Management
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - 8787:80
  krakend_ce:
    image: devopsfaith/krakend:1.3.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "6000:8080"
      - "6001:8090"
    depends_on:
      - jaeger

  # mongo:
  #   image: mongo:3.6.4
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - "mongo_data:/data/db"
  #   networks:
  #     - backend
  #   restart: always